version: "3.7"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "${PROJECT_NAME}_traefik"
    command:
      - "--configFile=/etc/traefik/traefik.${DEPLOY_MODE}.yml"
      - "--certificatesResolvers.resolver.acme.email=${EMAIL}"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/etc/letsencrypt"
      - "./traefik.${DEPLOY_MODE}.yml:/etc/traefik/traefik.${DEPLOY_MODE}.yml:ro"

  go:
    build:
      context: "."
      dockerfile: "docker-services/go/Dockerfile"
    image: "ipolanskis/${PROJECT_NAME}_go:latest"
    container_name: "${PROJECT_NAME}_go"
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go_service.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.go_service.entrypoints=websecure"
      - "traefik.http.routers.go_service.tls.certresolver=resolver"
