version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker-services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - goapp

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email ilja.polanskis.work@gmail.com --agree-tos --no-eff-email --staging -d captain-php.com
    depends_on:
      - nginx

  goapp:
    build:
      context: .
      dockerfile: docker-services/goapp/Dockerfile
    image: ipolanskis/goapp:latest
    ports:
      - "8080:8080"
