version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - goapp

  goapp:
    build:
      context: .
      dockerfile: docker-services/goapp/Dockerfile
    ports:
      - "8080:8080"
