version: '3'

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker-services/nginx:/etc/nginx/user_conf.d
      - nginx_secrets:/etc/letsencrypt
    environment:
      - CERTBOT_EMAIL
    depends_on:
      - goapp

  goapp:
    build:
      context: .
      dockerfile: docker-services/goapp/Dockerfile
    image: ipolanskis/goapp:latest
    ports:
      - "8080:8080"

volumes:
  nginx_secrets:
