log:
  level: ERROR

api:
  insecure: false

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: resolver

certificatesResolvers:
  resolver:
    acme:
      storage: "/etc/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web
